apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kubernetes-sigs/external-dns.git"
    targetRevision: v0.14.2
    path: charts/external-dns
    helm:
      values: |
        provider: cloudflare
        sources:
          - ingress
        policy: sync
        registry: txt
        domainFilters:
          - "ecvlsolutions.com"
        logLevel: info
        interval: 1m
        rbac:
          create: true
        serviceAccount:
          create: true
          name: "external-dns"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: api-token
          - name: CF_ZONE_ID
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: zone-id
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependencies:
    - name: ingress-nginx
