replicaCount: 1

image:
  repository: adservice
  tag: 0.1.0-kubernetes.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9555
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

env:
  PORT: "9555"
  DISABLE_PROFILER: "1"

podSecurityContext: {}
securityContext: {}

livenessProbe:
  grpc:
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  grpc:
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 