# Number of replicas to deploy
replicaCount: 1

# Container image configuration
image:
  repository: cartservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

# Service configuration
service:
  type: {{ .Values.global.service.type }}
  port: 7070

# Resource configuration
resources:
  limits:
    cpu: {{ .Values.global.resources.limits.cpu }}
    memory: {{ .Values.global.resources.limits.memory }}
  requests:
    cpu: {{ .Values.global.resources.requests.cpu }}
    memory: {{ .Values.global.resources.requests.memory }}

# Environment variables
env:
  PORT: {{ .Values.global.env.PORT }}
  REDIS_ADDR: {{ .Values.global.env.REDIS_ADDR }}

# Security context
podSecurityContext:
  fsGroup: {{ .Values.global.podSecurityContext.fsGroup }}

securityContext:
  runAsUser: {{ .Values.global.securityContext.runAsUser }}
  runAsNonRoot: {{ .Values.global.securityContext.runAsNonRoot }}

# Health check configuration
livenessProbe:
  httpGet:
    path: /health
    port: 7070
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 7070
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Redis configuration
redis-cart:
  persistence:
    enabled: {{ .Values.redis-cart.persistence.enabled }}
    size: {{ .Values.redis-cart.persistence.size }}
    storageClass: {{ .Values.redis-cart.persistence.storageClass }}
    accessMode: {{ .Values.redis-cart.persistence.accessMode }}

 