replicaCount: 1

image:
  repository: shoppingassistantservice
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 512Mi

env:
  PORT: "8080"
  DISABLE_PROFILER: "0"
  PROJECT_ID: "online-boutique"
  REGION: "us-central1"
  ALLOYDB_DATABASE_NAME: "online-boutique"
  ALLOYDB_TABLE_NAME: "shopping-assistant"
  ALLOYDB_CLUSTER_NAME: "online-boutique-cluster"
  ALLOYDB_INSTANCE_NAME: "online-boutique-instance"
  ALLOYDB_SECRET_NAME: "online-boutique-secret"
  PGPASSWORD: "password"

podSecurityContext:
  fsGroup: {}

securityContext:
  runAsUser: {}
  runAsNonRoot: {}

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 