replicaCount: 1

image:
  repository: shoppingassistantservice
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

env:
  PORT: "8080"
  PROJECT_ID: "online-boutique"
  REGION: "uksouth"
  DB_HOST: "online-boutique-postgres.postgres.database.azure.com"
  DB_NAME: "shopping_assistant"
  DB_USER: "postgres"
  DB_PORT: "5432"
  DB_SSL_MODE: "require"
  DISABLE_PROFILER: "1"

podSecurityContext: {}

securityContext: {}

livenessProbe:
  grpc:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  grpc:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 