apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ecvanlare/aks-microservices-gitops-demo.git'
    targetRevision: dev
    path: cluster/workloads
    directory:
      recurse: true
      include: "**/Chart.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - cert-manager
    - ingress-nginx
    - external-dns
