apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-of-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ecvanlare/aks-microservices-gitops-demo.git'
    targetRevision: dev
    path: cluster/infrastructure
    directory:
      recurse: true
      include: "**/*-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10 