trigger: none

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: 'enabled'
  - name: DOCKER_BUILD_ARGS
    value: '--pull'
  - name: BUILD_CACHE_FROM
    value: 'type=registry,ref=$(ACR_NAME).azurecr.io/$(serviceName):latest'

stages:
- stage: Build
  displayName: 'Build and Push Images'
  jobs:
  - template: templates/docker/build.yml
    parameters:
      acrName: $(ACR_NAME)
      resourceGroup: $(RESOURCE_GROUP)
      version: $(Build.BuildNumber)
      services:
        cartservice:
          serviceName: cartservice
          dockerfile: 'src/cartservice/src/Dockerfile'
          context: 'src/cartservice/src'
        productcatalogservice:
          serviceName: productcatalogservice
          dockerfile: 'src/productcatalogservice/Dockerfile'
          context: 'src/productcatalogservice'
        currencyservice:
          serviceName: currencyservice
          dockerfile: 'src/currencyservice/Dockerfile'
          context: 'src/currencyservice'
        emailservice:
          serviceName: emailservice
          dockerfile: 'src/emailservice/Dockerfile'
          context: 'src/emailservice'
        paymentservice:
          serviceName: paymentservice
          dockerfile: 'src/paymentservice/Dockerfile'
          context: 'src/paymentservice'
        shippingservice:
          serviceName: shippingservice
          dockerfile: 'src/shippingservice/Dockerfile'
          context: 'src/shippingservice'
        recommendationservice:
          serviceName: recommendationservice
          dockerfile: 'src/recommendationservice/Dockerfile'
          context: 'src/recommendationservice'
        adservice:
          serviceName: adservice
          dockerfile: 'src/adservice/Dockerfile'
          context: 'src/adservice'
        checkoutservice:
          serviceName: checkoutservice
          dockerfile: 'src/checkoutservice/Dockerfile'
          context: 'src/checkoutservice'
        shoppingassistantservice:
          serviceName: shoppingassistantservice
          dockerfile: 'src/shoppingassistantservice/Dockerfile'
          context: 'src/shoppingassistantservice'
        frontend:
          serviceName: frontend
          dockerfile: 'src/frontend/Dockerfile'
          context: 'src/frontend'
      maxParallel: 4
      retryCount: 2
      dockerBuildArgs: $(DOCKER_BUILD_ARGS)
      buildCacheFrom: $(BUILD_CACHE_FROM) 