trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'src/**'
      - '.azure/pipelines/**'
      - 'terraform/**'

variables:
  - group: online-boutique.common
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: 'enabled'
  - name: DOCKER_BUILD_ARGS
    value: '--no-cache --pull'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - template: templates/docker/build.yml
    parameters:
      acrName: $(ACR_NAME)
      resourceGroup: $(RESOURCE_GROUP)
      services:
        cartservice:
          dockerfile: 'src/cartservice/src/Dockerfile'
          context: 'src/cartservice/src'
        productcatalogservice:
          dockerfile: 'src/productcatalogservice/Dockerfile'
          context: 'src/productcatalogservice'
        currencyservice:
          dockerfile: 'src/currencyservice/Dockerfile'
          context: 'src/currencyservice'
        emailservice:
          dockerfile: 'src/emailservice/Dockerfile'
          context: 'src/emailservice'
        paymentservice:
          dockerfile: 'src/paymentservice/Dockerfile'
          context: 'src/paymentservice'
        shippingservice:
          dockerfile: 'src/shippingservice/Dockerfile'
          context: 'src/shippingservice'
        recommendationservice:
          dockerfile: 'src/recommendationservice/Dockerfile'
          context: 'src/recommendationservice'
        adservice:
          dockerfile: 'src/adservice/Dockerfile'
          context: 'src/adservice'
        checkoutservice:
          dockerfile: 'src/checkoutservice/Dockerfile'
          context: 'src/checkoutservice'
        shoppingassistantservice:
          dockerfile: 'src/shoppingassistantservice/Dockerfile'
          context: 'src/shoppingassistantservice'
        frontend:
          dockerfile: 'src/frontend/Dockerfile'
          context: 'src/frontend'
      maxParallel: 4
      retryCount: 2
      dockerBuildArgs: $(DOCKER_BUILD_ARGS) 