apiVersion: v2
name: online-boutique-chart
description: A Helm chart for Online Boutique microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: "0.1.0"
    repository: "file://../frontend"
  - name: adservice
    version: "0.1.0"
    repository: "file://../adservice"
  - name: cartservice
    version: "0.1.0"
    repository: "file://../cartservice"
  - name: checkoutservice
    version: "0.1.0"
    repository: "file://../checkoutservice"
  - name: currencyservice
    version: "0.1.0"
    repository: "file://../currencyservice"
  - name: emailservice
    version: "0.1.0"
    repository: "file://../emailservice"
  - name: paymentservice
    version: "0.1.0"
    repository: "file://../paymentservice"
  - name: productcatalogservice
    version: "0.1.0"
    repository: "file://../productcatalogservice"
  - name: recommendationservice
    version: "0.1.0"
    repository: "file://../recommendationservice"
  - name: redis-cart
    version: "0.1.0"
    repository: "file://../redis-cart"
  - name: shippingservice
    version: "0.1.0"
    repository: "file://../shippingservice"
  - name: shoppingassistantservice
    version: "0.1.0"
    repository: "file://../shoppingassistantservice" 