# Global values shared across all services
# These values are inherited by all subcharts unless overridden
global:
  # Image configuration shared across all services
  image:
    registry: acronlineboutique.azurecr.io  # Container registry URL
    pullPolicy: IfNotPresent               # Image pull policy
    tag: latest                            # Image tag

  # Default resource limits and requests for all services
  # Can be overridden per service in their respective sections
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # Common service configuration
  service:
    type: ClusterIP  # Default service type

  # Common environment variables shared across services
  env:
    PORT: "8080"              # Default service port
    DISABLE_PROFILER: "1"     # Disable profiler by default

  # Common health check configuration
  healthCheck:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Service-specific configurations
# These values override the global values for each service

frontend:
  # Frontend service specific resource configuration
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080

adservice:
  service:
    port: 9555
  env:
    MAX_ADS_TO_SERVE: "5"  # Maximum number of ads to serve
  # Security context for the ad service
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true

cartservice:
  service:
    port: 7070
  env:
    REDIS_ADDR: "redis-cart:6379"  # Redis connection address

checkoutservice:
  service:
    port: 5050
  env:
    # Service dependencies for checkout process
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    EMAIL_SERVICE_ADDR: "emailservice:8080"
    PAYMENT_SERVICE_ADDR: "paymentservice:50051"

currencyservice:
  service:
    port: 7000
  env:
    ALLOWED_CURRENCIES: "USD,EUR,JPY,GBP,TRY"  # Supported currencies

emailservice:
  service:
    port: 8080

paymentservice:
  service:
    port: 50051

productcatalogservice:
  service:
    port: 3550

recommendationservice:
  service:
    port: 8080
  env:
    # Service dependencies for recommendations
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"

shippingservice:
  service:
    port: 50051
  env:
    ALLOWED_CURRENCIES: "USD,EUR,JPY,GBP,TRY"  # Supported currencies for shipping

shoppingassistantservice:
  service:
    port: 8080
  env:
    # AlloyDB configuration - these should be overridden in production
    PROJECT_ID: "online-boutique"  # Default project ID
    REGION: "us-central1"          # Default region
    ALLOYDB_DATABASE_NAME: "shopping_assistant"  # Default database name
    ALLOYDB_TABLE_NAME: "shopping_history"       # Default table name
    ALLOYDB_CLUSTER_NAME: "shopping-cluster"     # Default cluster name
    ALLOYDB_INSTANCE_NAME: "shopping-instance"   # Default instance name
    ALLOYDB_SECRET_NAME: "alloydb-credentials"   # Default secret name
  # Security context for the shopping assistant service
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true

# Redis configuration for cart service
redis-cart:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 100Mi
      storageClass: "standard"
      accessMode: ReadWriteOnce
  service:
    port: 6379
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi 