# Global values shared across all services
global:
  image:
    registry: acronlineboutique.azurecr.io
    pullPolicy: IfNotPresent
    tag: latest

  # Common resource configurations
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # Common service configurations
  service:
    type: ClusterIP

  # Common environment variables
  env:
    PORT: "8080"

  # Service addresses for inter-service communication
  serviceAddresses:
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    AD_SERVICE_ADDR: "adservice:9555"
    SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8080"

# Service-specific overrides
frontend:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080

productcatalogservice:
  service:
    port: 3550

currencyservice:
  service:
    port: 7000

cartservice:
  service:
    port: 7070

recommendationservice:
  service:
    port: 8080

shippingservice:
  service:
    port: 50051

checkoutservice:
  service:
    port: 5050

adservice:
  service:
    port: 9555

shoppingassistantservice:
  service:
    port: 8080

redis-cart:
  persistence:
    enabled: true
    size: 100Mi
    storageClass: "standard"
    accessMode: ReadWriteOnce 