replicaCount: 1

image:
  repository: checkoutservice
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5050
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

env:
  PORT: "5050"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"

podSecurityContext: {}
securityContext: {}

livenessProbe:
  httpGet:
    path: /health
    port: 5050
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5050
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 