trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Common variables from variable groups
  - group: online-boutique.common    # Common variables (like AZURE_SUBSCRIPTION)
  
  # Terraform-specific variables
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
  - name: TERRAFORM_TEMPLATE
    value: '../../templates/terraform/infrastructure-terraform.yml'

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    displayName: 'Terraform Validate'
    steps:
    - template: ${{ variables.TERRAFORM_TEMPLATE }}
      parameters:
        workingDirectory: '$(TERRAFORM_DIR)'
        command: 'validate'

# Destroy stage requires manual approval in the 'infrastructure' environment
- stage: Destroy
  displayName: 'Destroy Infrastructure'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - deployment: Destroy
    displayName: 'Terraform Destroy'
    environment: 'infrastructure'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ${{ variables.TERRAFORM_TEMPLATE }}
            parameters:
              workingDirectory: '$(TERRAFORM_DIR)'
              command: 'destroy'
