# This pipeline handles the main infrastructure operations: validate, plan, and apply
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/infrastructure/**

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common    # Common variables (like AZURE_SUBSCRIPTION)
  - group: terraform.infrastructure  # Infrastructure-specific variables
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: '../../templates/terraform/terraform.yml'

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    displayName: 'Terraform Validate'
    steps:
    - template: ${{ variables.TERRAFORM_TEMPLATE }}
      parameters:
        workingDirectory: '$(TERRAFORM_DIR)'
        command: 'validate'

- stage: Plan
  displayName: 'Plan Changes'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: Plan
    displayName: 'Terraform Plan'
    steps:
    - template: ${{ variables.TERRAFORM_TEMPLATE }}
      parameters:
        workingDirectory: '$(TERRAFORM_DIR)'
        command: 'plan'

# Apply stage requires manual approval in the 'infrastructure' environment
- stage: Apply
  displayName: 'Apply Changes'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: 'Terraform Apply'
    environment: 'infrastructure'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Terraform Plan'
            inputs:
              artifactName: 'tfplan'
              targetPath: '$(TERRAFORM_DIR)'
              runVersion: 'latest'
          - template: ${{ variables.TERRAFORM_TEMPLATE }}
            parameters:
              workingDirectory: '$(TERRAFORM_DIR)'
              command: 'apply'