# This pipeline handles the main infrastructure operations: validate, plan, and apply
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/infrastructure/**

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    displayName: 'Terraform Validate'
    steps:
    - template: ../../templates/terraform/infrastructure-terraform.yml
      parameters:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
        command: 'validate'

- stage: Plan
  displayName: 'Plan Changes'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: Plan
    displayName: 'Terraform Plan'
    steps:
    - template: ../../templates/terraform/infrastructure-terraform.yml
      parameters:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
        command: 'plan'

# Apply stage requires manual approval in the 'infrastructure' environment
- stage: Apply
  displayName: 'Apply Changes'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: 'Terraform Apply'
    environment: 'infrastructure'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Terraform Plan'
            inputs:
              artifactName: 'tfplan'
              targetPath: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
              runVersion: 'latest'
          - template: ../../templates/terraform/terraform.yml
            parameters:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
              command: 'apply'