# Terraform destroy pipeline - destroys infrastructure (use with caution!)
trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: terraform.infrastructure
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: '../../templates/terraform/infrastructure-terraform.yml'

jobs:
- job: Plan
  displayName: 'Terraform Plan Destroy'
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'plan'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(TERRAFORM_DIR)/tfplan'
      artifact: 'terraform-plan'
      publishLocation: 'pipeline'

- deployment: Destroy
  displayName: 'Terraform Destroy'
  dependsOn: Plan
  condition: succeeded()
  environment: 'infrastructure-destroy'  # Separate environment with additional approvals
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: terraform
        - task: DownloadPipelineArtifact@2
          inputs:
            artifactName: 'terraform-plan'
            targetPath: '$(TERRAFORM_DIR)'
        - template: ${{ variables.TERRAFORM_TEMPLATE }}
          parameters:
            workingDirectory: '$(TERRAFORM_DIR)'
            command: 'destroy' 