# Terraform apply pipeline - plans and applies changes
trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
  - name: TERRAFORM_TEMPLATE
    value: '../../templates/terraform/infrastructure-terraform.yml'

jobs:
- job: Plan
  displayName: 'Terraform Plan'
  steps:
  - checkout:
      path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'plan'

- deployment: Apply
  displayName: 'Terraform Apply'
  dependsOn: Plan
  condition: succeeded()
  environment: 'infrastructure'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout:
            path: terraform
        - template: ${{ variables.TERRAFORM_TEMPLATE }}
          parameters:
            workingDirectory: '$(TERRAFORM_DIR)'
            command: 'apply' 