prometheusOperator:
  createCustomResource: false

grafana:
  # Admin password (change this in production!)
  adminPassword: "admin123"
  
  # Persistent storage for dashboards and configs
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "managed-csi"
    accessMode: ReadWriteOnce
  
  # Security settings
  security:
    adminUser: "admin"
    adminPassword: "admin123"
  
  # Default dashboards and datasources
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/default
  
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      kubernetes-pods:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
      kubernetes-nodes:
        gnetId: 6418
        revision: 1
        datasource: Prometheus
  
  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.ecvlsolutions.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: grafana.ecvlsolutions.com
    tls:
      - hosts:
          - grafana.ecvlsolutions.com
        secretName: grafana-tls
  
  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.ecvlsolutions.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: prometheus.ecvlsolutions.com
    tls:
      - hosts:
          - prometheus.ecvlsolutions.com
        secretName: prometheus-tls 