replicaCount: 1

image:
  repository: cartservice
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7070
  annotations: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 768Mi

env:
  PORT: "7070"
  REDIS_ADDR: "redis-cart:6379"

# User pool tolerations
tolerations:
  - key: "userpool"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Node affinity - require user pool
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: agentpool
          operator: In
          values:
          - userpool

# Node placement - inherits from parent chart global values

podSecurityContext: {}
securityContext: {}

livenessProbe:
  grpc:
    port: 7070
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  grpc:
    port: 7070
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3