parameters:
  workingDirectory: ''
  checkovFramework: 'terraform' # terraform, arm, kubernetes, etc.
  failOnHigh: true

steps:
- script: |
    pip install --upgrade pip checkov
    
    echo "Running Checkov security scan (JSON output)..."
    checkov -d . \
      --framework ${{ parameters.checkovFramework }} \
      --skip-path terraform/bootstrap \
      --output json --output-file checkov-results.json \
      --soft-fail

    echo "Running Checkov security scan (JUnit output)..."
    checkov -d . \
      --framework ${{ parameters.checkovFramework }} \
      --skip-path terraform/bootstrap \
      --output junit --output-file checkov-results.xml \
      --soft-fail

    echo "Checkov scan completed."
  displayName: 'Checkov Security Scan'
  workingDirectory: ${{ parameters.workingDirectory }}

- task: PublishTestResults@2
  displayName: 'Publish Checkov Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'checkov-results.xml'
    searchFolder: '${{ parameters.workingDirectory }}'
    testRunTitle: 'Checkov Security Scan'
    publishRunAttachments: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Checkov Report'
  condition: always()
  inputs:
    PathtoPublish: '${{ parameters.workingDirectory }}/checkov-results.json'
    ArtifactName: 'CheckovReport'