parameters:
  workingDirectory: ''
  checkovFramework: 'terraform'  # Framework for Checkov
  failOnHigh: true  # Whether to fail pipeline on high severity issues

steps:
- script: |
    echo "Installing Checkov..."
    pip install checkov
    echo "Running Checkov security scan..."
    checkov -d . --framework ${{ parameters.checkovFramework }} --output json --output-file-path checkov-results.json --soft-fail
    echo "Checkov scan completed. Results:"
    cat checkov-results.json
  displayName: 'Run Checkov Security Scan'
  workingDirectory: ${{ parameters.workingDirectory }} 