trigger: none

pr: none 

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'online-boutique.common'
  - group: 'online-boutique.kubernetes'
  - group: 'online-boutique.gitops'

stages:
- stage: SyncApplication
  displayName: 'Sync Application Configuration'
  jobs:
  - job: SyncApplicationConfig
    displayName: 'Sync Application with ArgoCD'
    steps:
    - checkout: self
      displayName: 'Checkout repository'

    - template: templates/azure-auth.yml
      parameters:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        resourceGroup: $(RESOURCE_GROUP)
        aksClusterName: $(AKS_CLUSTER_NAME)
        namespace: 'argocd'

    - template: templates/gitops-sync.yml
      parameters:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        appName: 'apps-of-apps'
        appYamlPath: 'cluster/root/apps-of-apps.yaml'
        syncMessage: 'Syncing Application Configuration'
