trigger: none

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "online-boutique.common"
  - group: "online-boutique.kubernetes"
  - group: "online-boutique.gitops"

stages:
  - stage: SyncInfrastructure
    displayName: "Sync Infrastructure Configuration"
    jobs:
      - job: SyncInfrastructureConfig
        displayName: "Sync Infrastructure with ArgoCD"
        steps:
          - checkout: self
            displayName: "Checkout repository"

          - template: templates/azure-auth.yml
            parameters:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              resourceGroup: $(RESOURCE_GROUP)
              aksClusterName: $(AKS_CLUSTER_NAME)
              namespace: "argocd"

          - template: templates/gitops-sync.yml
            parameters:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              appName: "infra-of-infra"
              appYamlPath: "cluster/root/infra-of-infra.yaml"
              syncMessage: "Syncing Infrastructure Configuration"
