# Application CD Pipeline - Deploy to Environments
trigger: none  # CD should not auto-trigger, only manual or from CI

pr: none  # CD should not run on PRs

variables:
  - group: 'online-boutique.common'
  - group: 'online-boutique.kubernetes'
  - group: 'online-boutique.gitops'
  - name: VM_IMAGE
    value: 'ubuntu-latest'

pool:
  vmImage: $(VM_IMAGE)

stages:
  - stage: GetBuildInfo
    displayName: 'Get Build Information'
    jobs:
    - job: GetInfo
      steps:
      - checkout: self
        fetchDepth: 0
        
      - template: templates/versioning/gitversion.yml
        parameters:
          name: 'SetGitVersion'
          fetchDepth: 0
          useConfigFile: false
          
      - template: templates/build/download-build-artifacts.yml
        parameters:
          gitDepth: 0
      


  - stage: UpdateGitOps
    displayName: 'Update GitOps with New Image Tags'
    dependsOn: GetBuildInfo
    condition: succeeded()
    variables:
      SEMVER: $[ stageDependencies.GetBuildInfo.GetInfo.outputs['ExtractSemver.SEMVER'] ]
      BUILT_SERVICES_LIST: $[ stageDependencies.GetBuildInfo.GetInfo.outputs['BuiltServices.BUILT_SERVICES_LIST'] ]
    jobs:
    - job: UpdateGitOpsValues
      displayName: 'Update GitOps Repository with New Image Tags'
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - checkout: self
        fetchDepth: 0
        
      - template: templates/gitops/gitops-update.yml
        parameters:
          semver: $(SEMVER)
          builtServices: $(BUILT_SERVICES_LIST)
          gitopsRepoUrl: $(GITOPS_REPO_URL)
          gitopsBranch: $(GITOPS_BRANCH)

  - stage: DeployToDev
    displayName: 'Deploy to Development Environment'
    dependsOn: UpdateGitOps
    condition: succeeded()
    variables:
      - group: 'online-boutique.dev'
      - group: 'online-boutique.common'
      - group: 'online-boutique.kubernetes'
      - name: SEMVER
        value: $[ stageDependencies.GetBuildInfo.GetInfo.outputs['ExtractSemver.SEMVER'] ]
    jobs:
    - deployment: DeployToDev
      environment: 'development'
      pool:
        vmImage: $(VM_IMAGE)
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            

            
            - template: templates/gitops/argocd-deploy.yml
              parameters:
                includeVerification: true
                semver: $(SEMVER)
                useArgoCD: true
                argocdNamespace: $(ARGOCD_NAMESPACE)
                gitopsRepoUrl: $(GITOPS_REPO_URL)
                gitopsBranch: $(GITOPS_BRANCH)

  - stage: DeployToProduction
    displayName: 'Deploy to Production Environment'
    dependsOn: DeployToDev
    condition: succeeded()
    variables:
      - group: 'online-boutique.prod'
      - group: 'online-boutique.common'
      - group: 'online-boutique.kubernetes'
      - name: SEMVER
        value: $[ stageDependencies.GetBuildInfo.GetInfo.outputs['ExtractSemver.SEMVER'] ]
    jobs:
    - deployment: DeployToProduction
      environment: 'production'
      pool:
        vmImage: $(VM_IMAGE)
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            

            
            - template: templates/gitops/argocd-deploy.yml
              parameters:
                includeVerification: true
                semver: $(SEMVER)
                useArgoCD: true
                argocdNamespace: $(ARGOCD_NAMESPACE)
                gitopsRepoUrl: $(GITOPS_REPO_URL)
                gitopsBranch: $(GITOPS_BRANCH)

  - stage: PostDeploymentVerification
    displayName: 'Post-Deployment Verification'
    dependsOn: DeployToProduction
    condition: succeeded()
    variables:
      - group: 'online-boutique.common'
      - group: 'online-boutique.kubernetes'
      - name: SEMVER
        value: $[ stageDependencies.GetBuildInfo.GetInfo.outputs['ExtractSemver.SEMVER'] ]
    jobs:
    - job: VerifyDeployment
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - checkout: self
    
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'deployment-summary'
          publishLocation: 'pipeline' 