# Application CI pipeline - scans source code for vulnerabilities (Part 1 of Hybrid Security)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/**
      
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - name: TRIVY_CI_TEMPLATE
    value: 'templates/trivy/trivy-ci.yml'

stages:
- stage: Security
  displayName: 'Source Code Security Scanning'
  dependsOn: []
  jobs:
  - job: TrivyScan
    displayName: 'Trivy Source Code Vulnerability Scan'
    timeoutInMinutes: 20
    steps:
    - checkout: self
    
    - template: ${{ variables.TRIVY_CI_TEMPLATE }}
      parameters:
        scanPath: 'src'
        failOnHigh: true
        severityThreshold: 'HIGH'

