trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - "src/**"
      - "online-boutique-chart/**"

variables:
  - group: 'online-boutique.common'
  - group: 'online-boutique.docker'
  - group: 'online-boutique.kubernetes'
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: VM_IMAGE
    value: 'ubuntu-22.04'

pool:
  vmImage: $(VM_IMAGE)

stages:
  - stage: DetectChanges
    displayName: 'Detect Changed Services and Calculate Version'
    jobs:
    - job: AnalyzeChanges
      steps:
      - template: ../templates/gitversion/gitversion-template.yml
        parameters:
          name: 'GitVersion'
          fetchDepth: 0
          useConfigFile: false

      - template: ../templates/detect-changes-task.yml
        parameters:
          gitDepth: 1
          sourceDir: 'src'
          chartDir: 'online-boutique-chart'
          acrName: $(ACR_NAME)
          resourceGroup: $(RESOURCE_GROUP)
          azureSubscription: $(AZURE_SUBSCRIPTION)

  # Debug Stage - Temporary
  - stage: DebugOutput
    displayName: 'Debug Output Variables'
    dependsOn: DetectChanges
    condition: succeeded()
    jobs:
    - job: Debug
      steps:
      - script: |
          echo "=== Debug Output Variables ==="
          echo "Testing if variables are accessible..."
          echo "====================================="
        displayName: 'Debug Output Variables'
      
      - script: |
          echo "=== Simple Debug Test ==="
          echo "If you see this, the debug stage is working"
          echo "The real test is whether BuildAllServices stage runs"
          echo "====================================="
        displayName: 'Simple Debug Test'

  # Conditional Build Stages
  - stage: BuildAllServices
    displayName: 'Build All Services (ACR Empty)'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAll
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - script: |
          echo "=== BuildAllServices Stage Started ==="
          echo "✅ This stage is running because ACR is empty"
          echo "SEMVER: $(SEMVER)"
          echo "BUILD_ALL condition was evaluated as true"
          echo "====================================="
        displayName: 'Build All Services Info'
      
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: cartservice
            - name: frontend
            - name: productcatalogservice
            - name: currencyservice
            - name: emailservice
            - name: paymentservice
            - name: shippingservice
            - name: recommendationservice
            - name: adservice
            - name: checkoutservice
            - name: shoppingassistantservice

  # Individual Build Stages (for normal changes)
  - stage: BuildCartService
    displayName: 'Build Cart Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), and(ne(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'), contains(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.SERVICES_TO_BUILD'], 'cartservice')))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: cartservice

  - stage: BuildFrontend
    displayName: 'Build Frontend'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: frontend

  - stage: BuildProductCatalogService
    displayName: 'Build Product Catalog Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: productcatalogservice

  - stage: BuildCurrencyService
    displayName: 'Build Currency Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: currencyservice

  - stage: BuildEmailService
    displayName: 'Build Email Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: emailservice

  - stage: BuildPaymentService
    displayName: 'Build Payment Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: paymentservice

  - stage: BuildShippingService
    displayName: 'Build Shipping Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: shippingservice

  - stage: BuildRecommendationService
    displayName: 'Build Recommendation Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: recommendationservice

  - stage: BuildAdService
    displayName: 'Build Ad Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: adservice

  - stage: BuildCheckoutService
    displayName: 'Build Checkout Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: checkoutservice

  - stage: BuildShoppingAssistantService
    displayName: 'Build Shopping Assistant Service'
    dependsOn: DetectChanges
    condition: and(succeeded(), eq(dependencies.DetectChanges.outputs['AnalyzeChanges.DetectChanges.BUILD_ALL'], 'true'))
    variables:
      SEMVER: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - job: BuildAndPush
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - template: ../templates/build-service-tasks.yml
        parameters:
          services:
            - name: shoppingassistantservice

  - stage: DeployToDev
    displayName: 'Deploy to Dev Environment'
    dependsOn: 
      - BuildAllServices
      - BuildCartService
      - BuildFrontend
      - BuildProductCatalogService
      - BuildCurrencyService
      - BuildEmailService
      - BuildPaymentService
      - BuildShippingService
      - BuildRecommendationService
      - BuildAdService
      - BuildCheckoutService
      - BuildShoppingAssistantService
    condition: succeeded()
    variables:
      - group: 'online-boutique.dev'
      - name: SEMVER
        value: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - deployment: Deploy
      environment: 'online-boutique-dev'
      pool:
        vmImage: $(VM_IMAGE)
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../templates/deploy-service-tasks.yml
              parameters:
                namespace: $(NAMESPACE)
                releaseName: $(RELEASE_NAME)
                includeVerification: true

  - stage: DeployToProduction
    displayName: 'Deploy to Production Environment'
    dependsOn: DeployToDev
    condition: succeeded()
    variables:
      - name: SEMVER
        value: $[ dependencies.DetectChanges.outputs['AnalyzeChanges.SetVersionOutputs.SEMVER'] ]
    jobs:
    - deployment: Deploy
      environment: 'online-boutique-prod'
      pool:
        vmImage: $(VM_IMAGE)
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../templates/deploy-service-tasks.yml
              parameters:
                namespace: $(NAMESPACE)
                releaseName: $(RELEASE_NAME)
                includeVerification: true 