trigger: none

# Main CI/CD Pipeline
# This is the entry point for the complete CI/CD process

variables:
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: VM_IMAGE
    value: 'ubuntu-latest'
  - name: NAMESPACE
    value: 'online-boutique'
  - name: RELEASE_NAME
    value: 'online-boutique'

stages:
- stage: Version
  displayName: 'Calculate Semantic Version'
  variables:
    - group: online-boutique.common
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'version'
      vmImage: $(VM_IMAGE)

- stage: Package
  displayName: 'Package Container Images'
  dependsOn: Version
  condition: succeeded()
  variables:
    - group: online-boutique.docker
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'package'
      vmImage: $(VM_IMAGE)
      packageMaxParallel: 4
      packageRetryCount: 2
      packageTimeoutMinutes: 30

- stage: Validate
  displayName: 'Validate Helm Chart'
  dependsOn: 
    - Version
    - Package
  condition: succeeded()
  variables:
    - group: online-boutique.common
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'validate'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Deploy
  displayName: 'Deploy to Environment'
  dependsOn: 
    - Version
    - Package
    - Validate
  condition: and(succeeded(), eq(dependencies.Package.result, 'Succeeded'), eq(dependencies.Validate.result, 'Succeeded'))
  variables:
    - group: online-boutique.kubernetes
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'deploy'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Verify
  displayName: 'Verify Deployment'
  dependsOn: Deploy
  condition: succeeded()
  variables:
    - group: online-boutique.kubernetes
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'verify'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME) 