trigger: none

# Main CI/CD Pipeline
# This is the entry point for the complete CI/CD process

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - group: online-boutique.kubernetes

stages:
- stage: CI_CD
  displayName: 'Complete CI/CD Process'
  jobs:
  - template: ../templates/ci-cd-template.yml
    parameters:
      # Package Parameters
      packageServices: true
      packageParallel: 4
      packageRetryCount: 2
      packageTimeout: 30
      
      # Environment Parameters
      deployEnvironment: 'main'
      deployNamespace: 'online-boutique'
      deployReleaseName: 'online-boutique'
      deployTimeout: '10m'
      deployWait: true
      deployAtomic: true
      deployMaxHistory: 5
      deployDryRun: false
      deployForce: false
      deployCleanupOnFail: true
      
      # Chart Parameters
      chartPath: 'online-boutique-chart'
      valuesFile: 'values.yaml'
      
      # Infrastructure Parameters
      vmImage: 'ubuntu-latest'
      helmVersion: '3.12.0' 