trigger: none

# Main CI/CD Pipeline
# This is the entry point for the complete CI/CD process

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - group: online-boutique.kubernetes
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: 'enabled'
  - name: DOCKER_BUILD_ARGS
    value: '--pull'
  - name: BUILD_CACHE_FROM
    value: 'type=registry,ref=$(ACR_NAME).azurecr.io/$(serviceName):$(SEMVER)'
  - name: BUILD_CACHE_TO
    value: 'type=registry,ref=$(ACR_NAME).azurecr.io/$(serviceName):$(SEMVER)'
  
  # Agent pool configuration
  - name: VM_IMAGE
    value: 'ubuntu-latest'

stages:
- stage: Version
  displayName: 'Calculate Semantic Version'
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'version'
      vmImage: $(VM_IMAGE)

- stage: Package
  displayName: 'Package Container Images'
  dependsOn: Version
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'package'
      vmImage: $(VM_IMAGE)
      packageMaxParallel: 4
      packageRetryCount: 2
      packageTimeoutMinutes: 30

- stage: Validate
  displayName: 'Validate Helm Chart'
  dependsOn: 
    - Version
    - Package
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'validate'
      vmImage: $(VM_IMAGE)
      chartPath: 'online-boutique-chart'
      valuesFile: 'values.yaml'
      deployReleaseName: 'online-boutique'
      deployNamespace: 'online-boutique'
      helmVersion: '3.12.0'

- stage: Deploy
  displayName: 'Deploy to Environment'
  dependsOn: 
    - Version
    - Package
    - Validate
  condition: and(succeeded(), eq(dependencies.Package.result, 'Succeeded'), eq(dependencies.Validate.result, 'Succeeded'))
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'deploy'
      vmImage: $(VM_IMAGE)
      deployEnvironment: 'main'
      deployNamespace: 'online-boutique'
      deployReleaseName: 'online-boutique'
      chartPath: 'online-boutique-chart'
      valuesFile: 'values.yaml'
      helmVersion: '3.12.0'
      helmTimeout: '10m'
      helmMaxHistory: 5

- stage: Verify
  displayName: 'Verify Deployment'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'verify'
      vmImage: $(VM_IMAGE)
      deployEnvironment: 'main'
      deployNamespace: 'online-boutique'
      deployReleaseName: 'online-boutique'
      podReadyTimeout: 300 