trigger: none

# Main CI/CD Pipeline
# This is the entry point for the complete CI/CD process

variables:
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: VM_IMAGE
    value: 'ubuntu-latest'

stages:
- stage: Version
  variables:
    - group: online-boutique.common
  displayName: 'Calculate Semantic Version'
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'version'
      vmImage: $(VM_IMAGE)

- stage: Package
  variables:
    - group: online-boutique.common
    - group: online-boutique.docker
    - group: online-boutique.kubernetes
  displayName: 'Package Container Images'
  dependsOn: Version
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'package'
      vmImage: $(VM_IMAGE)
      packageMaxParallel: 4
      packageRetryCount: 2
      packageTimeoutMinutes: 30

- stage: Validate
  variables:
    - group: online-boutique.common
    - group: online-boutique.kubernetes
  displayName: 'Validate Helm Chart'
  dependsOn: 
    - Version
    - Package
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'validate'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Deploy
  variables:
    - group: online-boutique.common
    - group: online-boutique.kubernetes
  displayName: 'Deploy to Environment'
  dependsOn: 
    - Version
    - Package
    - Validate
  condition: and(succeeded(), eq(dependencies.Package.result, 'Succeeded'), eq(dependencies.Validate.result, 'Succeeded'))
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'deploy'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Verify
  variables:
    - group: online-boutique.common
    - group: online-boutique.kubernetes
  displayName: 'Verify Deployment'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'verify'
      vmImage: $(VM_IMAGE)
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME) 