trigger: none

# Main CI/CD Pipeline
# This is the entry point for the complete CI/CD process

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - group: online-boutique.kubernetes
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: VM_IMAGE
    value: 'ubuntu-latest'

stages:
- stage: Version
  displayName: 'Calculate Semantic Version'
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'version'

- stage: Package
  displayName: 'Package Container Images'
  dependsOn: Version
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'package'
      packageMaxParallel: 4
      packageRetryCount: 2
      packageTimeoutMinutes: 30

- stage: Validate
  displayName: 'Validate Helm Chart'
  dependsOn: 
    - Version
    - Package
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'validate'
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Deploy
  displayName: 'Deploy to Environment'
  dependsOn: 
    - Version
    - Package
    - Validate
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'deploy'
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME)

- stage: Verify
  displayName: 'Verify Deployment'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - template: ../templates/ci-cd-jobs.yml
    parameters:
      jobType: 'verify'
      namespace: $(NAMESPACE)
      releaseName: $(RELEASE_NAME) 