replicaCount: 1

image:
  repository: recommendationservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  DISABLE_PROFILER: "1"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8080" 