replicaCount: 1

image:
  repository: adservice
  # tag and pullPolicy are inherited from global.image

service:
  # type is inherited from global.service.type
  port: 9555

# resources are inherited from global.resources unless overridden in the umbrella chart

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

livenessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

env:
  # PORT is inherited from global.env.PORT
  DISABLE_PROFILER: "1"
  MAX_ADS_TO_SERVE: "5" 