# Number of replicas to deploy
replicaCount: 1

# Container image configuration
image:
  repository: adservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

# Service configuration
service:
  type: {{ .Values.global.service.type }}
  port: 9555

# Resource configuration
resources:
  limits:
    cpu: {{ .Values.global.resources.limits.cpu }}
    memory: {{ .Values.global.resources.limits.memory }}
  requests:
    cpu: {{ .Values.global.resources.requests.cpu }}
    memory: {{ .Values.global.resources.requests.memory }}

# Environment variables
env:
  PORT: {{ .Values.global.env.PORT }}
  DISABLE_PROFILER: {{ .Values.global.env.DISABLE_PROFILER }}
  MAX_ADS_TO_SERVE: {{ .Values.adservice.env.MAX_ADS_TO_SERVE }}

# Security context
podSecurityContext:
  fsGroup: {{ .Values.adservice.podSecurityContext.fsGroup }}

securityContext:
  runAsUser: {{ .Values.adservice.securityContext.runAsUser }}
  runAsNonRoot: {{ .Values.adservice.securityContext.runAsNonRoot }}

# Health check configuration
livenessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 