image:
  repository: bitnami/redis
  tag: 7.4.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  size: 100Mi
  storageClass: "managed-csi"
  accessMode: ReadWriteOnce

auth:
  enabled: false
#   existingSecret: redis-password
#   existingSecretPasswordKey: redis-password

allowEmptyPassword: true

# User pool tolerations
tolerations:
  - key: "userpool"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Node affinity - require user pool
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: agentpool
          operator: In
          values:
          - userpool

# Redis configuration
command: []
dataPath: /data
volumeName: redis-data
redisConfig: false  # Enable to use ConfigMap for Redis configuration

livenessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# volumeMounts:
#   - name: secrets-store-inline
#     mountPath: "/mnt/secrets-store"
#     readOnly: true

# volumes:
#   - name: secrets-store-inline
#     csi:
#       driver: secrets-store.csi.k8s.io
#       readOnly: true
#       volumeAttributes:
#         secretProviderClass: "azure-keyvault"