global:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

adservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/adservice
    tag: v0.1.0

cartservice:
  enabled: true
  replicaCount: 2
  image:
    repository: acronlineboutique.azurecr.io/cartservice
    tag: v0.1.0
  env:
    REDIS_ADDR: "redis-cart:6379"
  ports:
    grpc: 7070

checkoutservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/checkoutservice
    tag: v0.1.0

currencyservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/currencyservice
    tag: v0.1.0

emailservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/emailservice
    tag: v0.1.0

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: acronlineboutique.azurecr.io/frontend
    tag: v0.1.0

paymentservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/paymentservice
    tag: v0.1.0

productcatalogservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/productcatalogservice
    tag: v0.1.0

recommendationservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/recommendationservice
    tag: v0.1.0

redis-cart:
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/redis
    tag: v0.1.0

shippingservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/shippingservice
    tag: v0.1.0

shoppingassistantservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/shoppingassistantservice
    tag: v0.1.0