global:
  image:
    registry: acronlineboutique.azurecr.io
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

adservice:
  enabled: true
  replicaCount: 1
  image:
    repository: adservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 9555
    annotations: {}

cartservice:
  enabled: true
  replicaCount: 2
  image:
    repository: cartservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 7070
    annotations: {}
  env:
    REDIS_ADDR: "redis-cart:6379"

checkoutservice:
  enabled: true
  replicaCount: 1
  image:
    repository: checkoutservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 5050
    annotations: {}

currencyservice:
  enabled: true
  replicaCount: 1
  image:
    repository: currencyservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 7000
    annotations: {}

emailservice:
  enabled: true
  replicaCount: 1
  image:
    repository: emailservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: frontend
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

paymentservice:
  enabled: true
  replicaCount: 1
  image:
    repository: paymentservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 50051
    annotations: {}

productcatalogservice:
  enabled: true
  replicaCount: 1
  image:
    repository: productcatalogservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 3550
    annotations: {}

recommendationservice:
  enabled: true
  replicaCount: 1
  image:
    repository: recommendationservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

redis-cart:
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/redis
    tag: v7.4.1
  service:
    type: ClusterIP
    port: 6379

shippingservice:
  enabled: true
  replicaCount: 1
  image:
    repository: shippingservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 50051
    annotations: {}

shoppingassistantservice:
  enabled: true
  replicaCount: 1
  image:
    repository: shoppingassistantservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}