global:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

adservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/adservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080      # HTTP port for adservice
    annotations: {}

cartservice:
  enabled: true
  replicaCount: 2
  image:
    repository: acronlineboutique.azurecr.io/cartservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080      # HTTP port for cartservice
    annotations: {}
  env:
    REDIS_ADDR: "redis-cart:6379"

checkoutservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/checkoutservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

currencyservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/currencyservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

emailservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/emailservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: acronlineboutique.azurecr.io/frontend
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 80        # Typical frontend port (can be 8080 or 80)
    annotations: {}


paymentservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/paymentservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

productcatalogservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/productcatalogservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

recommendationservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/recommendationservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

redis-cart:
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/redis
    tag: v7.4.1

shippingservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/shippingservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

shoppingassistantservice:
  enabled: true
  replicaCount: 1
  image:
    repository: acronlineboutique.azurecr.io/shoppingassistantservice
    tag: v0.1.0
  service:
    type: ClusterIP
    port: 8080
    annotations: {}