# Infrastructure CD pipeline - plans and applies changes
trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: terraform.infrastructure
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: 'templates/terraform-template.yml'

jobs:
- job: Plan
  displayName: 'Infrastructure Plan'
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'plan'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(TERRAFORM_DIR)/tfplan'
      artifact: 'infrastructure-plan'
      publishLocation: 'pipeline'

- deployment: Apply
  displayName: 'Infrastructure Apply'
  dependsOn: Plan
  condition: succeeded()
  environment: 'infrastructure'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: terraform
        - task: DownloadPipelineArtifact@2
          inputs:
            artifactName: 'infrastructure-plan'
            targetPath: '$(TERRAFORM_DIR)'
        - template: ${{ variables.TERRAFORM_TEMPLATE }}
          parameters:
            workingDirectory: '$(TERRAFORM_DIR)'
            command: 'apply' 