# Infrastructure CD pipeline - plans and applies changes with approval gates
trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: online-boutique.infrastructure
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: 'templates/terraform.yml'

stages:
- stage: Plan
  displayName: 'Plan Infrastructure Changes'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: Plan
    displayName: 'Create Infrastructure Plan'
    steps:
    - checkout: self
      path: terraform
    - template: ${{ variables.TERRAFORM_TEMPLATE }}
      parameters:
        workingDirectory: '$(TERRAFORM_DIR)'
        command: 'plan'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(TERRAFORM_DIR)/tfplan'
        artifact: 'infrastructure-plan'
        publishLocation: 'pipeline'

- stage: Apply
  displayName: 'Apply Infrastructure Changes'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: 'Apply Infrastructure Changes'
    environment: 'infrastructure'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            path: terraform
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'infrastructure-plan'
              targetPath: '$(TERRAFORM_DIR)'
          - template: ${{ variables.TERRAFORM_TEMPLATE }}
            parameters:
              workingDirectory: '$(TERRAFORM_DIR)'
              command: 'apply' 