# Infrastructure CI pipeline - validates and plans changes
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

pr: none  # Disable PR triggers - only run manually

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: terraform.infrastructure
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: 'templates/terraform-template.yml'

jobs:
- job: Validate
  displayName: 'Infrastructure Validate'
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'validate'

- job: Plan
  displayName: 'Infrastructure Plan'
  dependsOn: Validate
  condition: succeeded()
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'plan' 