# Terraform plan pipeline - validates and plans changes
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common
  - group: terraform.infrastructure
  - name: TERRAFORM_DIR
    value: '$(System.DefaultWorkingDirectory)/terraform'
  - name: TERRAFORM_TEMPLATE
    value: '../templates/terraform/terraform-template.yml'

jobs:
- job: Validate
  displayName: 'Terraform Validate'
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'validate'

- job: Plan
  displayName: 'Terraform Plan'
  dependsOn: Validate
  condition: succeeded()
  steps:
  - checkout: self
    path: terraform
  - template: ${{ variables.TERRAFORM_TEMPLATE }}
    parameters:
      workingDirectory: '$(TERRAFORM_DIR)'
      command: 'plan' 