replicaCount: 1

image:
  repository: shoppingassistantservice
  # tag and pullPolicy are inherited from global.image

service:
  # type is inherited from global.service.type
  port: 8080

# resources are inherited from global.resources unless overridden in the umbrella chart

env:
  # PORT is inherited from global.env.PORT
  PRODUCT_CATALOG_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.PRODUCT_CATALOG_SERVICE_ADDR }}"
  CURRENCY_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CURRENCY_SERVICE_ADDR }}"
  CART_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CART_SERVICE_ADDR }}"
  RECOMMENDATION_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.RECOMMENDATION_SERVICE_ADDR }}"
  SHIPPING_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.SHIPPING_SERVICE_ADDR }}"
  CHECKOUT_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CHECKOUT_SERVICE_ADDR }}"
  AD_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.AD_SERVICE_ADDR }}"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 