trigger: none

variables:
  - group: online-boutique.common
  - group: online-boutique.docker
  - name: APP_SOURCE_DIR
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: 'enabled'
  - name: DOCKER_BUILD_ARGS
    value: '--pull'
  - name: BUILD_CACHE_FROM
    value: 'type=registry,ref=$(ACR_NAME).azurecr.io/$(serviceName):latest'
  - name: BUILD_TEMPLATE
    value: '../templates/docker/acr-build.yml'

stages:
- stage: Build
  displayName: 'Build and Push Container Images'
  jobs:
  - template: ${{ variables.BUILD_TEMPLATE }}
    parameters:
      acrName: $(ACR_NAME)
      resourceGroup: $(RESOURCE_GROUP)
      services:
        cartservice:
          serviceName: cartservice
          dockerfile: '$(APP_SOURCE_DIR)/cartservice/src/Dockerfile'
          context: 'src/cartservice/src'
        productcatalogservice:
          serviceName: productcatalogservice
          dockerfile: '$(APP_SOURCE_DIR)/productcatalogservice/Dockerfile'
          context: 'src/productcatalogservice'
        currencyservice:
          serviceName: currencyservice
          dockerfile: '$(APP_SOURCE_DIR)/currencyservice/Dockerfile'
          context: 'src/currencyservice'
        emailservice:
          serviceName: emailservice
          dockerfile: '$(APP_SOURCE_DIR)/emailservice/Dockerfile'
          context: 'src/emailservice'
        paymentservice:
          serviceName: paymentservice
          dockerfile: '$(APP_SOURCE_DIR)/paymentservice/Dockerfile'
          context: 'src/paymentservice'
        shippingservice:
          serviceName: shippingservice
          dockerfile: '$(APP_SOURCE_DIR)/shippingservice/Dockerfile'
          context: 'src/shippingservice'
        recommendationservice:
          serviceName: recommendationservice
          dockerfile: '$(APP_SOURCE_DIR)/recommendationservice/Dockerfile'
          context: 'src/recommendationservice'
        adservice:
          serviceName: adservice
          dockerfile: '$(APP_SOURCE_DIR)/adservice/Dockerfile'
          context: 'src/adservice'
        checkoutservice:
          serviceName: checkoutservice
          dockerfile: '$(APP_SOURCE_DIR)/checkoutservice/Dockerfile'
          context: 'src/checkoutservice'
        shoppingassistantservice:
          serviceName: shoppingassistantservice
          dockerfile: '$(APP_SOURCE_DIR)/shoppingassistantservice/Dockerfile'
          context: 'src/shoppingassistantservice'
        frontend:
          serviceName: frontend
          dockerfile: '$(APP_SOURCE_DIR)/frontend/Dockerfile'
          context: 'src/frontend'
      maxParallel: 4
      retryCount: 2
      dockerBuildArgs: $(DOCKER_BUILD_ARGS)
      buildCacheFrom: $(BUILD_CACHE_FROM)
      timeoutInMinutes: 30 