replicaCount: 1

image:
  repository: currencyservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

service:
  type: ClusterIP
  port: 7000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  PORT: "7000"
  PROJECT_ID: ""
  DISABLE_PROFILER: "1"
