# Update GitOps Values Template
# Updates Helm chart values.yaml with new image tags for built services

parameters:
  semver: ''  # Required: Semantic version for image tags
  builtServices: ''  # Required: Space-separated list of services that were built
  gitopsRepoUrl: ''  # Required: GitOps repository URL
  gitopsBranch: ''  # Required: GitOps repository branch
  prTitle: ''  # Required: PR title
  prDescription: ''  # Required: PR description

steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      echo "=== Update GitOps Values ==="
      echo "Semver: ${{ parameters.semver }}"
      echo "Built services: ${{ parameters.builtServices }}"
      echo "GitOps repo: ${{ parameters.gitopsRepoUrl }}"
      echo "GitOps branch: ${{ parameters.gitopsBranch }}"

      # Install GitHub CLI if not available
      if ! command -v gh &> /dev/null; then
        echo "Installing GitHub CLI..."
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        apt update && apt install -y gh
      fi

      # Clone GitOps repository
      git clone --branch "${{ parameters.gitopsBranch }}" "${{ parameters.gitopsRepoUrl }}" gitops-repo
      cd gitops-repo

      # Update values.yaml for each built service
      VALUES_FILE="helm-charts/app-chart/values.yaml"
      
      if [ ! -f "$VALUES_FILE" ]; then
        echo "❌ Error: $VALUES_FILE not found"
        exit 1
      fi

      echo "Updating $VALUES_FILE..."
      
      # Convert space-separated services to array
      IFS=' ' read -ra SERVICES <<< "${{ parameters.builtServices }}"
      
      for service in "${SERVICES[@]}"; do
        if [ -n "$service" ]; then
          echo "Updating image tag for $service to ${{ parameters.semver }}"
          
          # Update the image tag for the specific service
          # Pattern: service_name: -> find the image.tag line within that service block
          sed -i "/^${service}:/,/^[a-zA-Z]/ s/^\([[:space:]]*tag:[[:space:]]*\).*/\1\"${{ parameters.semver }}\"/" "$VALUES_FILE"
        fi
      done

      # Show the updated values
      echo "Updated values.yaml:"
      cat "$VALUES_FILE"

      # Commit and push changes
      git config user.email "azure-pipeline@example.com"
      git config user.name "Azure Pipeline"
      
      git add "$VALUES_FILE"
      git commit -m "Update image tags to ${{ parameters.semver }} for services: ${{ parameters.builtServices }}"
      
      # Push changes
      git push origin "${{ parameters.gitopsBranch }}"
      
      # Create PR using GitHub CLI
      # Note: This requires GitHub token to be available as GITHUB_TOKEN environment variable
      if [ -n "$GITHUB_TOKEN" ]; then
        echo "$GITHUB_TOKEN" | gh auth login --with-token
        gh pr create \
          --title "${{ parameters.prTitle }}" \
          --body "${{ parameters.prDescription }}" \
          --head "${{ parameters.gitopsBranch }}" \
          --base main
      else
        echo "⚠️ Warning: GITHUB_TOKEN not available, skipping PR creation"
      fi

      echo "✅ GitOps values updated successfully"
    displayName: 'Update GitOps Values and Create PR'