replicaCount: 1

image:
  repository: adservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9555

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

livenessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 9555
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

env:
  PORT: "9555"
  DISABLE_PROFILER: "1"
  MAX_ADS_TO_SERVE: "5" 