# Code Quality Pipeline
# Runs all linting and formatting checks using the local script for consistency

trigger: none # No CI trigger
pr:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - .azure/**
      - cluster/**
      - terraform/**
      - scripts/**
      - src/**
      - .yamllint
      - README-linting.md

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CodeQuality
    displayName: "Code Quality Checks"
    jobs:
      - job: LintAndFormat
        displayName: "Lint & Format Check"
        continueOnError: true
        steps:
          - checkout: self
            fetchDepth: 1 # Shallow clone for speed

          # Install all required dependencies in one step
          - script: |
              set -e
              echo "🔧 Installing all code quality dependencies..."
              # Bash
              sudo apt-get install -y shellcheck shfmt
              # Prettier (for YAML formatting)
              sudo apt-get install -y npm
              npm install -g prettier
              # Terraform (for lint-local.sh)
              sudo apt-get install -y wget gpg
              wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt-get update && sudo apt-get install -y terraform
              # Existing tools
              pip3 install yamllint
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              # Install Helm (official script)
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            displayName: "Install All Linting Tools"

          # Run the local linting script (single source of truth)
          - script: |
              chmod +x ./scripts/lint-local.sh
              ./scripts/lint-local.sh
            displayName: "Run Local Linting Script"
            continueOnError: false

      - job: TerraformFmtCheck
        displayName: "Terraform Format Check"
        continueOnError: true
        steps:
          - checkout: self
            fetchDepth: 1
          - script: |
              set -e
              # Install Terraform from HashiCorp official repo for Ubuntu 24.04+
              sudo apt-get update && \
                sudo apt-get install -y wget gpg && \
                wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null && \
                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list && \
                sudo apt-get update && \
                sudo apt-get install -y terraform
              terraform fmt -check -recursive terraform/
            displayName: "Check Terraform Formatting"

      - job: TFLint
        displayName: "TFLint"
        continueOnError: true
        steps:
          - checkout: self
            fetchDepth: 1
          - script: |
              set -e
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              cd terraform
              tflint --init
              tflint --format=compact
            displayName: "Run TFLint"

      - job: HelmLint
        displayName: "Helm Lint"
        continueOnError: true
        steps:
          - checkout: self
            fetchDepth: 1
          - script: |
              set -e
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
              helm lint cluster/helm/online-boutique
            displayName: "Run Helm Lint"
