trigger: none

pr:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - src/**
      - package.json
      - requirements.txt
      - go.mod
      - build.gradle
      - pom.xml

pool:
  vmImage: ubuntu-latest

variables:
  - group: "online-boutique.devsecops"

stages:
  - stage: DependencyScan
    displayName: "Dependency Vulnerability Scan with Snyk"
    jobs:
      - job: SnykScan
        displayName: "Run Snyk on All Microservices"
        steps:
          - checkout: self
            fetchDepth: 1

          - task: UseNode@1
            inputs:
              version: '18.x'
            displayName: 'Install Node.js'

          - script: |
              echo "🔧 Installing Snyk CLI..."
              npm install -g snyk

              echo "🔐 Authenticating with Snyk..."
              snyk auth $(SNYK_TOKEN)

              echo "🔍 Scanning each service for vulnerable dependencies..."
              for dir in $(find src -maxdepth 2 -mindepth 1 -type d); do
                echo "📁 Scanning: $dir"
                snyk test --severity-threshold=high --all-projects --project-name="${dir}" || echo "⚠️ Snyk scan failed for $dir"
              done
            displayName: "Run Snyk Test on All Services"