trigger: none

pr:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - src/**
      - scripts/**
      - cluster/**
      - terraform/**
      - .azure/**
      - .gitignore

pool:
  vmImage: ubuntu-latest

stages:
  - stage: SecretScan
    displayName: "Secrets Detection with Gitleaks"
    jobs:
      - job: GitleaksScan
        displayName: "Run Gitleaks Secrets Scan"
        continueOnError: false
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0  # Required for Gitleaks to scan git history

          - script: |
              echo "📥 Installing Gitleaks..."
              GITLEAKS_VERSION="8.18.0"
              wget "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
              tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
              chmod +x gitleaks
              sudo mv gitleaks /usr/local/bin/

              echo "✅ Verifying Gitleaks installation..."
              gitleaks version

              echo "🔍 Running secrets scan with Gitleaks..."
              gitleaks detect --source . --report-format sarif --report-path gitleaks-report.sarif --exit-code 1
            displayName: "Run Gitleaks Scan"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: gitleaks-report.sarif
              artifactName: gitleaks-report
              publishLocation: 'Container'
            displayName: "Publish Gitleaks Report"