trigger: none

pr:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - src/**
      - scripts/**
      - cluster/**
      - terraform/**
      - .azure/**
      - .gitignore

pool:
  vmImage: ubuntu-latest

stages:
  - stage: SecretScan
    displayName: "Secrets Detection with Gitleaks"
    jobs:
      - job: GitleaksScan
        displayName: "Run Gitleaks Secrets Scan"
        continueOnError: false
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0  # Required for Gitleaks to scan git history

          - script: |
              echo "📥 Installing Gitleaks..."
              curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
              chmod +x gitleaks
              sudo mv gitleaks /usr/local/bin/

              echo "🔍 Running secrets scan with Gitleaks..."
              gitleaks detect --source . --report-format sarif --report-path gitleaks-report.sarif --exit-code 1
            displayName: "Run Gitleaks Scan"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: gitleaks-report.sarif
              artifactName: gitleaks-report
              publishLocation: 'Container'
            displayName: "Publish Gitleaks Report"