{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-chart.fullname" . }}-ingress
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ssl.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ssl.clusterIssuer | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{- if .Values.ssl.enabled }}true{{- else }}false{{- end }}"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.frontend.service.port }}
  {{- else }}
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.frontend.service.port }}
  {{- end }}
  {{- if .Values.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ include "helm-chart.fullname" . }}-tls
  {{- end }}
{{- end }} 