# Number of replicas to deploy
replicaCount: 1

# Container image configuration
image:
  repository: shippingservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

# Service configuration
service:
  type: {{ .Values.global.service.type }}
  port: 50051

# Resource configuration
resources:
  limits:
    cpu: {{ .Values.global.resources.limits.cpu }}
    memory: {{ .Values.global.resources.limits.memory }}
  requests:
    cpu: {{ .Values.global.resources.requests.cpu }}
    memory: {{ .Values.global.resources.requests.memory }}

# Environment variables
env:
  PORT: {{ .Values.global.env.PORT }}
  ALLOWED_CURRENCIES: {{ .Values.shippingservice.env.ALLOWED_CURRENCIES }}

# Health check configuration
livenessProbe:
  httpGet:
    path: /health
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 