replicaCount: 1

image:
  repository: cartservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7070

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  PORT: "7070"
  REDIS_ADDR: "redis-cart:6379"

 