trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common    # Common variables (like AZURE_SUBSCRIPTION)
  - group: terraform.application     # Application-specific variables

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    displayName: 'Terraform Validate'
    steps:
    - template: ../../templates/terraform/application-terraform.yml
      parameters:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        command: 'validate'

# Destroy stage requires manual approval in the 'application' environment
- stage: Destroy
  displayName: 'Destroy Infrastructure'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - deployment: Destroy
    displayName: 'Terraform Destroy'
    environment: 'application'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../../templates/terraform/application-terraform.yml
            parameters:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              command: 'apply'
              destroy: true
