trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: online-boutique.common    # Common variables (like AZURE_SUBSCRIPTION)
  - group: terraform.application     # Application-specific variables

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    displayName: 'Terraform Validate'
    steps:
    - template: ../../templates/terraform/application-terraform.yml
      parameters:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        command: 'validate'

- stage: Plan
  displayName: 'Plan Changes'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: Plan
    displayName: 'Terraform Plan'
    steps:
    - template: ../../templates/terraform/application-terraform.yml
      parameters:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        command: 'plan'

# Apply stage requires manual approval in the 'application' environment
- stage: Apply
  displayName: 'Apply Changes'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: 'Terraform Apply'
    environment: 'application'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../../templates/terraform/application-terraform.yml
            parameters:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              command: 'apply'
