replicaCount: 1

image:
  repository: paymentservice
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

service:
  type: ClusterIP
  port: 50051

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  PORT: "50051" 