replicaCount: 1

image:
  repository: acronlineboutique.azurecr.io/paymentservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  PORT: "50051" 