# Number of replicas to deploy
replicaCount: 1

# Container image configuration
image:
  repository: frontend
  tag: {{ .Values.global.image.tag }}
  pullPolicy: {{ .Values.global.image.pullPolicy }}

# Service configuration
service:
  type: {{ .Values.global.service.type }}
  port: 8080

# Resource configuration
resources:
  limits:
    cpu: {{ .Values.global.resources.limits.cpu }}
    memory: {{ .Values.global.resources.limits.memory }}
  requests:
    cpu: {{ .Values.global.resources.requests.cpu }}
    memory: {{ .Values.global.resources.requests.memory }}

# Environment variables
env:
  PORT: {{ .Values.global.env.PORT }}
  PRODUCT_CATALOG_SERVICE_ADDR: {{ .Values.global.serviceAddresses.PRODUCT_CATALOG_SERVICE_ADDR }}
  CURRENCY_SERVICE_ADDR: {{ .Values.global.serviceAddresses.CURRENCY_SERVICE_ADDR }}
  CART_SERVICE_ADDR: {{ .Values.global.serviceAddresses.CART_SERVICE_ADDR }}
  RECOMMENDATION_SERVICE_ADDR: {{ .Values.global.serviceAddresses.RECOMMENDATION_SERVICE_ADDR }}
  SHIPPING_SERVICE_ADDR: {{ .Values.global.serviceAddresses.SHIPPING_SERVICE_ADDR }}
  CHECKOUT_SERVICE_ADDR: {{ .Values.global.serviceAddresses.CHECKOUT_SERVICE_ADDR }}
  AD_SERVICE_ADDR: {{ .Values.global.serviceAddresses.AD_SERVICE_ADDR }}
  SHOPPING_ASSISTANT_SERVICE_ADDR: {{ .Values.global.serviceAddresses.SHOPPING_ASSISTANT_SERVICE_ADDR }} 