image:
  repository: bitnami/redis
  tag: 7.4.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  size: 100Mi
  storageClass: "managed-csi"
  accessMode: ReadWriteOnce

auth:
  enabled: false
#   existingSecret: redis-password
#   existingSecretPasswordKey: redis-password

allowEmptyPassword: true

livenessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3