replicaCount: 1

image:
  repository: redis
  tag: alpine
  pullPolicy: {{ .Values.global.image.pullPolicy }}

# Service configuration
service:
  type: {{ .Values.global.service.type }}
  port: 6379

# Resource configuration
resources:
  limits:
    cpu: {{ .Values.global.resources.limits.cpu }}
    memory: {{ .Values.global.resources.limits.memory }}
  requests:
    cpu: {{ .Values.global.resources.requests.cpu }}
    memory: {{ .Values.global.resources.requests.memory }}

# Security context inherited from global
podSecurityContext:
  fsGroup: {{ .Values.global.podSecurityContext.fsGroup }}
  runAsUser: {{ .Values.global.securityContext.runAsUser }}
  runAsNonRoot: {{ .Values.global.securityContext.runAsNonRoot }}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false  # Redis needs write access

persistence:
  enabled: true
  size: 100Mi
  storageClass: "standard"
  accessMode: ReadWriteOnce

livenessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

command:
  - "redis-server"
  - "--appendonly"
  - "yes" 