apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-of-infra
  namespace: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ecvanlare/azure-devops-online-boutique.git
    targetRevision: HEAD
    path: gitops/infrastructure/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10 