apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ecvanlare/online-boutique-private.git'
    targetRevision: argocd
    path: gitops/infrastructure/cert-manager/
    directory:
      include: [cluster-issuer.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - cert-manager
  # This app creates the ClusterIssuer after cert-manager is ready 