replicaCount: 1

image:
  repository: shippingservice
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 512Mi

env:
  PORT: "50051"

podSecurityContext: {}
securityContext: {}

livenessProbe:
  httpGet:
    path: /health
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 