apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:ecvanlare/online-boutique-private.git'
    targetRevision: argocd
    path: gitops/
    directory:
      recurse: true
      exclude: '**/cluster-issuer.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
  # This app bootstraps infrastructure apps first, excluding ClusterIssuer 