replicaCount: 1

image:
  repository: acronlineboutique.azurecr.io/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.PRODUCT_CATALOG_SERVICE_ADDR }}"
  CURRENCY_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CURRENCY_SERVICE_ADDR }}"
  CART_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CART_SERVICE_ADDR }}"
  RECOMMENDATION_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.RECOMMENDATION_SERVICE_ADDR }}"
  SHIPPING_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.SHIPPING_SERVICE_ADDR }}"
  CHECKOUT_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.CHECKOUT_SERVICE_ADDR }}"
  AD_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.AD_SERVICE_ADDR }}"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "{{ .Values.global.serviceAddresses.SHOPPING_ASSISTANT_SERVICE_ADDR }}" 